server:
  http_listen_port: 3200
  grpc_server_max_recv_msg_size: 4194304 # 4MB
  grpc_server_max_send_msg_size: 4194304

distributor:
  receivers:
    otlp:
      protocols:
        http: # Mantém apenas HTTP
          endpoint: 0.0.0.0:4318
        grpc:  
          endpoint: 0.0.0.0:4317

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
